# HTTP Configuration
http-enabled=true
http-port=8080

# Database Configuration
db=postgres
db-username=keycloak
db-password=keycloak
db-url=jdbc:postgresql://postgres-dc-a:5432/keycloak_dc_a

# Enable Workflows Engine Feature
features=workflows

# Register Custom Event Listener SPI
spi-events-listener-workflows-audit-listener-enabled=true
